  uses: dennisameling/ftp-upload-action@v1
  with:
    server: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USER }}
    password: ${{ secrets.FTP_PASSWORD }}
    local_dir: ./build/htlm/ # Should always end with /
    server_dir: ./ # Should always end with /

