name: Deploy to FTP v2

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: dennisameling/ftp-upload-action@v1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./build/html/
          server_dir: ./
